// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_status_history.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addCardStatusHistory = `-- name: AddCardStatusHistory :one
INSERT INTO "card-platform".card_status_history (
    uuid_card, 
    status
) VALUES ($1, $2)
RETURNING uuid, uuid_card, status, created_at
`

type AddCardStatusHistoryParams struct {
	UuidCard uuid.UUID `json:"uuid_card"`
	Status   string    `json:"status"`
}

func (q *Queries) AddCardStatusHistory(ctx context.Context, arg AddCardStatusHistoryParams) (CardPlatformCardStatusHistory, error) {
	row := q.db.QueryRow(ctx, addCardStatusHistory, arg.UuidCard, arg.Status)
	var i CardPlatformCardStatusHistory
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCardHistory = `-- name: GetCardHistory :many
SELECT uuid, uuid_card, status, created_at FROM "card-platform".card_status_history
WHERE uuid_card = $1
ORDER BY created_at DESC
`

func (q *Queries) GetCardHistory(ctx context.Context, uuidCard uuid.UUID) ([]CardPlatformCardStatusHistory, error) {
	rows, err := q.db.Query(ctx, getCardHistory, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformCardStatusHistory{}
	for rows.Next() {
		var i CardPlatformCardStatusHistory
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
