// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO "card-platform".cards (
    uuid_order, 
    has_laser, 
    has_magnet, 
    has_mifare_uid, 
    has_mifare, 
    has_java_card, 
    has_press, 
    has_temperature, 
    description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING uuid, uuid_order, has_laser, has_magnet, has_mifare_uid, has_mifare, has_java_card, has_press, has_temperature, is_done, description, created_at, updated_at
`

type CreateCardParams struct {
	UuidOrder      uuid.UUID   `json:"uuid_order"`
	HasLaser       bool        `json:"has_laser"`
	HasMagnet      bool        `json:"has_magnet"`
	HasMifareUid   bool        `json:"has_mifare_uid"`
	HasMifare      bool        `json:"has_mifare"`
	HasJavaCard    bool        `json:"has_java_card"`
	HasPress       bool        `json:"has_press"`
	HasTemperature bool        `json:"has_temperature"`
	Description    pgtype.Text `json:"description"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CardPlatformCard, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UuidOrder,
		arg.HasLaser,
		arg.HasMagnet,
		arg.HasMifareUid,
		arg.HasMifare,
		arg.HasJavaCard,
		arg.HasPress,
		arg.HasTemperature,
		arg.Description,
	)
	var i CardPlatformCard
	err := row.Scan(
		&i.Uuid,
		&i.UuidOrder,
		&i.HasLaser,
		&i.HasMagnet,
		&i.HasMifareUid,
		&i.HasMifare,
		&i.HasJavaCard,
		&i.HasPress,
		&i.HasTemperature,
		&i.IsDone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM "card-platform".cards
WHERE uuid = $1
`

func (q *Queries) DeleteCard(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCard, argUuid)
	return err
}

const getCard = `-- name: GetCard :one
SELECT uuid, uuid_order, has_laser, has_magnet, has_mifare_uid, has_mifare, has_java_card, has_press, has_temperature, is_done, description, created_at, updated_at FROM "card-platform".cards
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetCard(ctx context.Context, argUuid uuid.UUID) (CardPlatformCard, error) {
	row := q.db.QueryRow(ctx, getCard, argUuid)
	var i CardPlatformCard
	err := row.Scan(
		&i.Uuid,
		&i.UuidOrder,
		&i.HasLaser,
		&i.HasMagnet,
		&i.HasMifareUid,
		&i.HasMifare,
		&i.HasJavaCard,
		&i.HasPress,
		&i.HasTemperature,
		&i.IsDone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByOrder = `-- name: ListCardsByOrder :many
SELECT uuid, uuid_order, has_laser, has_magnet, has_mifare_uid, has_mifare, has_java_card, has_press, has_temperature, is_done, description, created_at, updated_at FROM "card-platform".cards
WHERE uuid_order = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCardsByOrder(ctx context.Context, uuidOrder uuid.UUID) ([]CardPlatformCard, error) {
	rows, err := q.db.Query(ctx, listCardsByOrder, uuidOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformCard{}
	for rows.Next() {
		var i CardPlatformCard
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidOrder,
			&i.HasLaser,
			&i.HasMagnet,
			&i.HasMifareUid,
			&i.HasMifare,
			&i.HasJavaCard,
			&i.HasPress,
			&i.HasTemperature,
			&i.IsDone,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardDoneStatus = `-- name: UpdateCardDoneStatus :one
UPDATE "card-platform".cards
SET is_done = $2
WHERE uuid = $1
RETURNING uuid, uuid_order, has_laser, has_magnet, has_mifare_uid, has_mifare, has_java_card, has_press, has_temperature, is_done, description, created_at, updated_at
`

type UpdateCardDoneStatusParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	IsDone bool      `json:"is_done"`
}

func (q *Queries) UpdateCardDoneStatus(ctx context.Context, arg UpdateCardDoneStatusParams) (CardPlatformCard, error) {
	row := q.db.QueryRow(ctx, updateCardDoneStatus, arg.Uuid, arg.IsDone)
	var i CardPlatformCard
	err := row.Scan(
		&i.Uuid,
		&i.UuidOrder,
		&i.HasLaser,
		&i.HasMagnet,
		&i.HasMifareUid,
		&i.HasMifare,
		&i.HasJavaCard,
		&i.HasPress,
		&i.HasTemperature,
		&i.IsDone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
