// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: laser_data.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getLaserDataByCard = `-- name: GetLaserDataByCard :many
SELECT uuid, uuid_card, side, row_no, content_type, content, created_at FROM "card-platform".laser_data
WHERE uuid_card = $1
`

func (q *Queries) GetLaserDataByCard(ctx context.Context, uuidCard uuid.UUID) ([]CardPlatformLaserDatum, error) {
	rows, err := q.db.Query(ctx, getLaserDataByCard, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformLaserDatum{}
	for rows.Next() {
		var i CardPlatformLaserDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.Side,
			&i.RowNo,
			&i.ContentType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLaserData = `-- name: UpsertLaserData :one
INSERT INTO "card-platform".laser_data (
    uuid_card, 
    side, 
    row_no, 
    content_type, 
    content
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (uuid_card, side, row_no) 
DO UPDATE SET 
    content_type = EXCLUDED.content_type,
    content = EXCLUDED.content,
    created_at = NOW()
RETURNING uuid, uuid_card, side, row_no, content_type, content, created_at
`

type UpsertLaserDataParams struct {
	UuidCard    uuid.UUID `json:"uuid_card"`
	Side        string    `json:"side"`
	RowNo       int32     `json:"row_no"`
	ContentType string    `json:"content_type"`
	Content     []byte    `json:"content"`
}

func (q *Queries) UpsertLaserData(ctx context.Context, arg UpsertLaserDataParams) (CardPlatformLaserDatum, error) {
	row := q.db.QueryRow(ctx, upsertLaserData,
		arg.UuidCard,
		arg.Side,
		arg.RowNo,
		arg.ContentType,
		arg.Content,
	)
	var i CardPlatformLaserDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Side,
		&i.RowNo,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
