// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magnet_data.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getMagnetDataByCard = `-- name: GetMagnetDataByCard :many
SELECT uuid, uuid_card, track_no, content, created_at FROM "card-platform".magnet_data
WHERE uuid_card = $1
`

func (q *Queries) GetMagnetDataByCard(ctx context.Context, uuidCard uuid.UUID) ([]CardPlatformMagnetDatum, error) {
	rows, err := q.db.Query(ctx, getMagnetDataByCard, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformMagnetDatum{}
	for rows.Next() {
		var i CardPlatformMagnetDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.TrackNo,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMagnetData = `-- name: UpsertMagnetData :one
INSERT INTO "card-platform".magnet_data (
    uuid_card, 
    track_no, 
    content
) VALUES ($1, $2, $3)
ON CONFLICT (uuid_card, track_no) 
DO UPDATE SET 
    content = EXCLUDED.content,
    created_at = NOW()
RETURNING uuid, uuid_card, track_no, content, created_at
`

type UpsertMagnetDataParams struct {
	UuidCard uuid.UUID `json:"uuid_card"`
	TrackNo  int32     `json:"track_no"`
	Content  []byte    `json:"content"`
}

func (q *Queries) UpsertMagnetData(ctx context.Context, arg UpsertMagnetDataParams) (CardPlatformMagnetDatum, error) {
	row := q.db.QueryRow(ctx, upsertMagnetData, arg.UuidCard, arg.TrackNo, arg.Content)
	var i CardPlatformMagnetDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.TrackNo,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
