// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mifare_data.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getMifareDataByCard = `-- name: GetMifareDataByCard :many
SELECT uuid, uuid_card, block_no, key_a, key_b, content, created_at FROM "card-platform".mifare_data
WHERE uuid_card = $1
`

func (q *Queries) GetMifareDataByCard(ctx context.Context, uuidCard uuid.UUID) ([]CardPlatformMifareDatum, error) {
	rows, err := q.db.Query(ctx, getMifareDataByCard, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformMifareDatum{}
	for rows.Next() {
		var i CardPlatformMifareDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.BlockNo,
			&i.KeyA,
			&i.KeyB,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMifareData = `-- name: UpsertMifareData :one
INSERT INTO "card-platform".mifare_data (
    uuid_card, 
    block_no, 
    key_a, 
    key_b, 
    content
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (uuid_card, block_no) 
DO UPDATE SET 
    key_a = EXCLUDED.key_a,
    key_b = EXCLUDED.key_b,
    content = EXCLUDED.content,
    created_at = NOW()
RETURNING uuid, uuid_card, block_no, key_a, key_b, content, created_at
`

type UpsertMifareDataParams struct {
	UuidCard uuid.UUID `json:"uuid_card"`
	BlockNo  int32     `json:"block_no"`
	KeyA     []byte    `json:"key_a"`
	KeyB     []byte    `json:"key_b"`
	Content  []byte    `json:"content"`
}

func (q *Queries) UpsertMifareData(ctx context.Context, arg UpsertMifareDataParams) (CardPlatformMifareDatum, error) {
	row := q.db.QueryRow(ctx, upsertMifareData,
		arg.UuidCard,
		arg.BlockNo,
		arg.KeyA,
		arg.KeyB,
		arg.Content,
	)
	var i CardPlatformMifareDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.BlockNo,
		&i.KeyA,
		&i.KeyB,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
