// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardPlatformCard struct {
	Uuid           uuid.UUID          `json:"uuid"`
	UuidOrder      uuid.UUID          `json:"uuid_order"`
	HasLaser       bool               `json:"has_laser"`
	HasMagnet      bool               `json:"has_magnet"`
	HasMifareUid   bool               `json:"has_mifare_uid"`
	HasMifare      bool               `json:"has_mifare"`
	HasJavaCard    bool               `json:"has_java_card"`
	HasPress       bool               `json:"has_press"`
	HasTemperature bool               `json:"has_temperature"`
	IsDone         bool               `json:"is_done"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CardPlatformCardStatusHistory struct {
	Uuid      uuid.UUID          `json:"uuid"`
	UuidCard  uuid.UUID          `json:"uuid_card"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CardPlatformLaserDatum struct {
	Uuid        uuid.UUID          `json:"uuid"`
	UuidCard    uuid.UUID          `json:"uuid_card"`
	Side        string             `json:"side"`
	RowNo       int32              `json:"row_no"`
	ContentType string             `json:"content_type"`
	Content     []byte             `json:"content"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CardPlatformMagnetDatum struct {
	Uuid      uuid.UUID          `json:"uuid"`
	UuidCard  uuid.UUID          `json:"uuid_card"`
	TrackNo   int32              `json:"track_no"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CardPlatformMifareDatum struct {
	Uuid      uuid.UUID          `json:"uuid"`
	UuidCard  uuid.UUID          `json:"uuid_card"`
	BlockNo   int32              `json:"block_no"`
	KeyA      []byte             `json:"key_a"`
	KeyB      []byte             `json:"key_b"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CardPlatformOrder struct {
	Uuid        uuid.UUID          `json:"uuid"`
	OrderName   string             `json:"order_name"`
	Status      string             `json:"status"`
	Description pgtype.Text        `json:"description"`
	OrderDate   pgtype.Timestamptz `json:"order_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
