// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO "card-platform".orders (
    order_name, 
    description
) VALUES ($1, $2)
RETURNING uuid, order_name, status, description, order_date, created_at, updated_at
`

type CreateOrderParams struct {
	OrderName   string      `json:"order_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CardPlatformOrder, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.OrderName, arg.Description)
	var i CardPlatformOrder
	err := row.Scan(
		&i.Uuid,
		&i.OrderName,
		&i.Status,
		&i.Description,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM "card-platform".orders
WHERE uuid = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, argUuid)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT uuid, order_name, status, description, order_date, created_at, updated_at FROM "card-platform".orders
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, argUuid uuid.UUID) (CardPlatformOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, argUuid)
	var i CardPlatformOrder
	err := row.Scan(
		&i.Uuid,
		&i.OrderName,
		&i.Status,
		&i.Description,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT uuid, order_name, status, description, order_date, created_at, updated_at FROM "card-platform".orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]CardPlatformOrder, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformOrder{}
	for rows.Next() {
		var i CardPlatformOrder
		if err := rows.Scan(
			&i.Uuid,
			&i.OrderName,
			&i.Status,
			&i.Description,
			&i.OrderDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE "card-platform".orders
SET status = $2
WHERE uuid = $1
RETURNING uuid, order_name, status, description, order_date, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (CardPlatformOrder, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Uuid, arg.Status)
	var i CardPlatformOrder
	err := row.Scan(
		&i.Uuid,
		&i.OrderName,
		&i.Status,
		&i.Description,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
