// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countCardsByOrderUUID = `-- name: CountCardsByOrderUUID :one
SELECT COUNT(*) AS count
FROM cards
WHERE uuid_order = ?
`

func (q *Queries) CountCardsByOrderUUID(ctx context.Context, uuidOrder string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsByOrderUUID, uuidOrder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDoneCardsByOrderUUID = `-- name: CountDoneCardsByOrderUUID :one
SELECT COUNT(*) AS count
FROM cards
WHERE uuid_order = ?
  AND is_done = 1
`

func (q *Queries) CountDoneCardsByOrderUUID(ctx context.Context, uuidOrder string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDoneCardsByOrderUUID, uuidOrder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (
    uuid,
    uuid_order,
    has_laser,
    has_magnet,
    has_mifare_uid,
    has_mifare,
    has_java_card,
    has_press,
    has_temperature,
    is_done,
    description,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCardParams struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.Uuid,
		arg.UuidOrder,
		arg.HasLaser,
		arg.HasMagnet,
		arg.HasMifareUid,
		arg.HasMifare,
		arg.HasJavaCard,
		arg.HasPress,
		arg.HasTemperature,
		arg.IsDone,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCardByUUID = `-- name: DeleteCardByUUID :exec
DELETE FROM cards
WHERE uuid = ?
`

func (q *Queries) DeleteCardByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteCardByUUID, uuid)
	return err
}

const getCardByUUID = `-- name: GetCardByUUID :one
SELECT
    uuid,
    uuid_order,
    has_laser,
    has_magnet,
    has_mifare_uid,
    has_mifare,
    has_java_card,
    has_press,
    has_temperature,
    is_done,
    description,
    created_at,
    updated_at
FROM cards
WHERE uuid = ?
LIMIT 1
`

type GetCardByUUIDRow struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) GetCardByUUID(ctx context.Context, uuid string) (GetCardByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCardByUUID, uuid)
	var i GetCardByUUIDRow
	err := row.Scan(
		&i.Uuid,
		&i.UuidOrder,
		&i.HasLaser,
		&i.HasMagnet,
		&i.HasMifareUid,
		&i.HasMifare,
		&i.HasJavaCard,
		&i.HasPress,
		&i.HasTemperature,
		&i.IsDone,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByOrderUUID = `-- name: ListCardsByOrderUUID :many
SELECT
    uuid,
    uuid_order,
    has_laser,
    has_magnet,
    has_mifare_uid,
    has_mifare,
    has_java_card,
    has_press,
    has_temperature,
    is_done,
    description,
    created_at,
    updated_at
FROM cards
WHERE uuid_order = ?
ORDER BY created_at DESC
`

type ListCardsByOrderUUIDRow struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) ListCardsByOrderUUID(ctx context.Context, uuidOrder string) ([]ListCardsByOrderUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByOrderUUID, uuidOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsByOrderUUIDRow{}
	for rows.Next() {
		var i ListCardsByOrderUUIDRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidOrder,
			&i.HasLaser,
			&i.HasMagnet,
			&i.HasMifareUid,
			&i.HasMifare,
			&i.HasJavaCard,
			&i.HasPress,
			&i.HasTemperature,
			&i.IsDone,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoneCardsByOrderUUID = `-- name: ListDoneCardsByOrderUUID :many
SELECT
    uuid,
    uuid_order,
    has_laser,
    has_magnet,
    has_mifare_uid,
    has_mifare,
    has_java_card,
    has_press,
    has_temperature,
    is_done,
    description,
    created_at,
    updated_at
FROM cards
WHERE uuid_order = ?
  AND is_done = 1
ORDER BY created_at DESC
`

type ListDoneCardsByOrderUUIDRow struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) ListDoneCardsByOrderUUID(ctx context.Context, uuidOrder string) ([]ListDoneCardsByOrderUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listDoneCardsByOrderUUID, uuidOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoneCardsByOrderUUIDRow{}
	for rows.Next() {
		var i ListDoneCardsByOrderUUIDRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidOrder,
			&i.HasLaser,
			&i.HasMagnet,
			&i.HasMifareUid,
			&i.HasMifare,
			&i.HasJavaCard,
			&i.HasPress,
			&i.HasTemperature,
			&i.IsDone,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCardsByOrderUUID = `-- name: ListPendingCardsByOrderUUID :many
SELECT
    uuid,
    uuid_order,
    has_laser,
    has_magnet,
    has_mifare_uid,
    has_mifare,
    has_java_card,
    has_press,
    has_temperature,
    is_done,
    description,
    created_at,
    updated_at
FROM cards
WHERE uuid_order = ?
  AND is_done = 0
ORDER BY created_at DESC
`

type ListPendingCardsByOrderUUIDRow struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

func (q *Queries) ListPendingCardsByOrderUUID(ctx context.Context, uuidOrder string) ([]ListPendingCardsByOrderUUIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingCardsByOrderUUID, uuidOrder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCardsByOrderUUIDRow{}
	for rows.Next() {
		var i ListPendingCardsByOrderUUIDRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidOrder,
			&i.HasLaser,
			&i.HasMagnet,
			&i.HasMifareUid,
			&i.HasMifare,
			&i.HasJavaCard,
			&i.HasPress,
			&i.HasTemperature,
			&i.IsDone,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardDescription = `-- name: UpdateCardDescription :exec
UPDATE cards
SET
    description = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateCardDescriptionParams struct {
	Description sql.NullString `json:"description"`
	UpdatedAt   int64          `json:"updated_at"`
	Uuid        string         `json:"uuid"`
}

func (q *Queries) UpdateCardDescription(ctx context.Context, arg UpdateCardDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateCardDescription, arg.Description, arg.UpdatedAt, arg.Uuid)
	return err
}

const updateCardDoneStatus = `-- name: UpdateCardDoneStatus :exec
UPDATE cards
SET
    is_done = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateCardDoneStatusParams struct {
	IsDone    int64  `json:"is_done"`
	UpdatedAt int64  `json:"updated_at"`
	Uuid      string `json:"uuid"`
}

func (q *Queries) UpdateCardDoneStatus(ctx context.Context, arg UpdateCardDoneStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCardDoneStatus, arg.IsDone, arg.UpdatedAt, arg.Uuid)
	return err
}

const updateCardFlagsAndDescription = `-- name: UpdateCardFlagsAndDescription :exec
UPDATE cards
SET
    has_laser = ?,
    has_magnet = ?,
    has_mifare_uid = ?,
    has_mifare = ?,
    has_java_card = ?,
    has_press = ?,
    has_temperature = ?,
    is_done = ?,
    description = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateCardFlagsAndDescriptionParams struct {
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	UpdatedAt      int64          `json:"updated_at"`
	Uuid           string         `json:"uuid"`
}

func (q *Queries) UpdateCardFlagsAndDescription(ctx context.Context, arg UpdateCardFlagsAndDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateCardFlagsAndDescription,
		arg.HasLaser,
		arg.HasMagnet,
		arg.HasMifareUid,
		arg.HasMifare,
		arg.HasJavaCard,
		arg.HasPress,
		arg.HasTemperature,
		arg.IsDone,
		arg.Description,
		arg.UpdatedAt,
		arg.Uuid,
	)
	return err
}
