// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_status_history.sql

package sqlc

import (
	"context"
)

const countCardStatusHistoryByCardUUID = `-- name: CountCardStatusHistoryByCardUUID :one
SELECT COUNT(*) AS count
FROM card_status_history
WHERE uuid_card = ?
`

func (q *Queries) CountCardStatusHistoryByCardUUID(ctx context.Context, uuidCard string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardStatusHistoryByCardUUID, uuidCard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCardStatusHistory = `-- name: CreateCardStatusHistory :exec
INSERT INTO card_status_history (
    uuid,
    uuid_card,
    status,
    created_at
) VALUES (?, ?, ?, ?)
`

type CreateCardStatusHistoryParams struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateCardStatusHistory(ctx context.Context, arg CreateCardStatusHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createCardStatusHistory,
		arg.Uuid,
		arg.UuidCard,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const deleteCardStatusHistoriesByCardUUID = `-- name: DeleteCardStatusHistoriesByCardUUID :exec
DELETE FROM card_status_history
WHERE uuid_card = ?
`

func (q *Queries) DeleteCardStatusHistoriesByCardUUID(ctx context.Context, uuidCard string) error {
	_, err := q.db.ExecContext(ctx, deleteCardStatusHistoriesByCardUUID, uuidCard)
	return err
}

const deleteCardStatusHistoryByUUID = `-- name: DeleteCardStatusHistoryByUUID :exec
DELETE FROM card_status_history
WHERE uuid = ?
`

func (q *Queries) DeleteCardStatusHistoryByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteCardStatusHistoryByUUID, uuid)
	return err
}

const getCardStatusHistoryByUUID = `-- name: GetCardStatusHistoryByUUID :one
SELECT
    uuid,
    uuid_card,
    status,
    created_at
FROM card_status_history
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetCardStatusHistoryByUUID(ctx context.Context, uuid string) (CardStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, getCardStatusHistoryByUUID, uuid)
	var i CardStatusHistory
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCardStatusByCardUUID = `-- name: GetLatestCardStatusByCardUUID :one
SELECT
    uuid,
    uuid_card,
    status,
    created_at
FROM card_status_history
WHERE uuid_card = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCardStatusByCardUUID(ctx context.Context, uuidCard string) (CardStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestCardStatusByCardUUID, uuidCard)
	var i CardStatusHistory
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listCardStatusHistoryByCardUUID = `-- name: ListCardStatusHistoryByCardUUID :many
SELECT
    uuid,
    uuid_card,
    status,
    created_at
FROM card_status_history
WHERE uuid_card = ?
ORDER BY created_at ASC
`

func (q *Queries) ListCardStatusHistoryByCardUUID(ctx context.Context, uuidCard string) ([]CardStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listCardStatusHistoryByCardUUID, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardStatusHistory{}
	for rows.Next() {
		var i CardStatusHistory
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
