// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: laser_data.sql

package sqlc

import (
	"context"
)

const countLaserDataByCardUUID = `-- name: CountLaserDataByCardUUID :one
SELECT COUNT(*) AS count
FROM card_platform_laser_data
WHERE uuid_card = ?
`

func (q *Queries) CountLaserDataByCardUUID(ctx context.Context, uuidCard string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLaserDataByCardUUID, uuidCard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLaserData = `-- name: CreateLaserData :exec
INSERT INTO card_platform_laser_data (
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateLaserDataParams struct {
	Uuid        string `json:"uuid"`
	UuidCard    string `json:"uuid_card"`
	Side        string `json:"side"`
	RowNo       int64  `json:"row_no"`
	ContentType string `json:"content_type"`
	Content     []byte `json:"content"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateLaserData(ctx context.Context, arg CreateLaserDataParams) error {
	_, err := q.db.ExecContext(ctx, createLaserData,
		arg.Uuid,
		arg.UuidCard,
		arg.Side,
		arg.RowNo,
		arg.ContentType,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteLaserDataByCardSideRow = `-- name: DeleteLaserDataByCardSideRow :exec
DELETE FROM card_platform_laser_data
WHERE uuid_card = ?
  AND side = ?
  AND row_no = ?
`

type DeleteLaserDataByCardSideRowParams struct {
	UuidCard string `json:"uuid_card"`
	Side     string `json:"side"`
	RowNo    int64  `json:"row_no"`
}

func (q *Queries) DeleteLaserDataByCardSideRow(ctx context.Context, arg DeleteLaserDataByCardSideRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteLaserDataByCardSideRow, arg.UuidCard, arg.Side, arg.RowNo)
	return err
}

const deleteLaserDataByCardUUID = `-- name: DeleteLaserDataByCardUUID :exec
DELETE FROM card_platform_laser_data
WHERE uuid_card = ?
`

func (q *Queries) DeleteLaserDataByCardUUID(ctx context.Context, uuidCard string) error {
	_, err := q.db.ExecContext(ctx, deleteLaserDataByCardUUID, uuidCard)
	return err
}

const deleteLaserDataByUUID = `-- name: DeleteLaserDataByUUID :exec
DELETE FROM card_platform_laser_data
WHERE uuid = ?
`

func (q *Queries) DeleteLaserDataByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteLaserDataByUUID, uuid)
	return err
}

const getLaserDataByCardSideRow = `-- name: GetLaserDataByCardSideRow :one
SELECT
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
FROM card_platform_laser_data
WHERE uuid_card = ?
  AND side = ?
  AND row_no = ?
LIMIT 1
`

type GetLaserDataByCardSideRowParams struct {
	UuidCard string `json:"uuid_card"`
	Side     string `json:"side"`
	RowNo    int64  `json:"row_no"`
}

func (q *Queries) GetLaserDataByCardSideRow(ctx context.Context, arg GetLaserDataByCardSideRowParams) (CardPlatformLaserDatum, error) {
	row := q.db.QueryRowContext(ctx, getLaserDataByCardSideRow, arg.UuidCard, arg.Side, arg.RowNo)
	var i CardPlatformLaserDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Side,
		&i.RowNo,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getLaserDataByUUID = `-- name: GetLaserDataByUUID :one
SELECT
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
FROM card_platform_laser_data
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetLaserDataByUUID(ctx context.Context, uuid string) (CardPlatformLaserDatum, error) {
	row := q.db.QueryRowContext(ctx, getLaserDataByUUID, uuid)
	var i CardPlatformLaserDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.Side,
		&i.RowNo,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listLaserDataByCardUUID = `-- name: ListLaserDataByCardUUID :many
SELECT
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
FROM card_platform_laser_data
WHERE uuid_card = ?
ORDER BY side ASC, row_no ASC
`

func (q *Queries) ListLaserDataByCardUUID(ctx context.Context, uuidCard string) ([]CardPlatformLaserDatum, error) {
	rows, err := q.db.QueryContext(ctx, listLaserDataByCardUUID, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformLaserDatum{}
	for rows.Next() {
		var i CardPlatformLaserDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.Side,
			&i.RowNo,
			&i.ContentType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLaserDataByCardUUIDAndSide = `-- name: ListLaserDataByCardUUIDAndSide :many
SELECT
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
FROM card_platform_laser_data
WHERE uuid_card = ?
  AND side = ?
ORDER BY row_no ASC
`

type ListLaserDataByCardUUIDAndSideParams struct {
	UuidCard string `json:"uuid_card"`
	Side     string `json:"side"`
}

func (q *Queries) ListLaserDataByCardUUIDAndSide(ctx context.Context, arg ListLaserDataByCardUUIDAndSideParams) ([]CardPlatformLaserDatum, error) {
	rows, err := q.db.QueryContext(ctx, listLaserDataByCardUUIDAndSide, arg.UuidCard, arg.Side)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformLaserDatum{}
	for rows.Next() {
		var i CardPlatformLaserDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.Side,
			&i.RowNo,
			&i.ContentType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLaserDataContent = `-- name: UpdateLaserDataContent :exec
UPDATE card_platform_laser_data
SET
    content_type = ?,
    content = ?
WHERE uuid = ?
`

type UpdateLaserDataContentParams struct {
	ContentType string `json:"content_type"`
	Content     []byte `json:"content"`
	Uuid        string `json:"uuid"`
}

func (q *Queries) UpdateLaserDataContent(ctx context.Context, arg UpdateLaserDataContentParams) error {
	_, err := q.db.ExecContext(ctx, updateLaserDataContent, arg.ContentType, arg.Content, arg.Uuid)
	return err
}

const upsertLaserData = `-- name: UpsertLaserData :exec
INSERT INTO card_platform_laser_data (
    uuid,
    uuid_card,
    side,
    row_no,
    content_type,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uuid_card, side, row_no) DO UPDATE SET
    content_type = excluded.content_type,
    content = excluded.content
`

type UpsertLaserDataParams struct {
	Uuid        string `json:"uuid"`
	UuidCard    string `json:"uuid_card"`
	Side        string `json:"side"`
	RowNo       int64  `json:"row_no"`
	ContentType string `json:"content_type"`
	Content     []byte `json:"content"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) UpsertLaserData(ctx context.Context, arg UpsertLaserDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertLaserData,
		arg.Uuid,
		arg.UuidCard,
		arg.Side,
		arg.RowNo,
		arg.ContentType,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
