// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magnet_data.sql

package sqlc

import (
	"context"
)

const countMagnetDataByCardUUID = `-- name: CountMagnetDataByCardUUID :one
SELECT COUNT(*) AS count
FROM card_platform_magnet_data
WHERE uuid_card = ?
`

func (q *Queries) CountMagnetDataByCardUUID(ctx context.Context, uuidCard string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMagnetDataByCardUUID, uuidCard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMagnetData = `-- name: CreateMagnetData :exec
INSERT INTO card_platform_magnet_data (
    uuid,
    uuid_card,
    track_no,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateMagnetDataParams struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	TrackNo   int64  `json:"track_no"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateMagnetData(ctx context.Context, arg CreateMagnetDataParams) error {
	_, err := q.db.ExecContext(ctx, createMagnetData,
		arg.Uuid,
		arg.UuidCard,
		arg.TrackNo,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteMagnetDataByCardTrack = `-- name: DeleteMagnetDataByCardTrack :exec
DELETE FROM card_platform_magnet_data
WHERE uuid_card = ?
  AND track_no = ?
`

type DeleteMagnetDataByCardTrackParams struct {
	UuidCard string `json:"uuid_card"`
	TrackNo  int64  `json:"track_no"`
}

func (q *Queries) DeleteMagnetDataByCardTrack(ctx context.Context, arg DeleteMagnetDataByCardTrackParams) error {
	_, err := q.db.ExecContext(ctx, deleteMagnetDataByCardTrack, arg.UuidCard, arg.TrackNo)
	return err
}

const deleteMagnetDataByCardUUID = `-- name: DeleteMagnetDataByCardUUID :exec
DELETE FROM card_platform_magnet_data
WHERE uuid_card = ?
`

func (q *Queries) DeleteMagnetDataByCardUUID(ctx context.Context, uuidCard string) error {
	_, err := q.db.ExecContext(ctx, deleteMagnetDataByCardUUID, uuidCard)
	return err
}

const deleteMagnetDataByUUID = `-- name: DeleteMagnetDataByUUID :exec
DELETE FROM card_platform_magnet_data
WHERE uuid = ?
`

func (q *Queries) DeleteMagnetDataByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteMagnetDataByUUID, uuid)
	return err
}

const getMagnetDataByCardTrack = `-- name: GetMagnetDataByCardTrack :one
SELECT
    uuid,
    uuid_card,
    track_no,
    content,
    created_at
FROM card_platform_magnet_data
WHERE uuid_card = ?
  AND track_no = ?
LIMIT 1
`

type GetMagnetDataByCardTrackParams struct {
	UuidCard string `json:"uuid_card"`
	TrackNo  int64  `json:"track_no"`
}

func (q *Queries) GetMagnetDataByCardTrack(ctx context.Context, arg GetMagnetDataByCardTrackParams) (CardPlatformMagnetDatum, error) {
	row := q.db.QueryRowContext(ctx, getMagnetDataByCardTrack, arg.UuidCard, arg.TrackNo)
	var i CardPlatformMagnetDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.TrackNo,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMagnetDataByUUID = `-- name: GetMagnetDataByUUID :one
SELECT
    uuid,
    uuid_card,
    track_no,
    content,
    created_at
FROM card_platform_magnet_data
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetMagnetDataByUUID(ctx context.Context, uuid string) (CardPlatformMagnetDatum, error) {
	row := q.db.QueryRowContext(ctx, getMagnetDataByUUID, uuid)
	var i CardPlatformMagnetDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.TrackNo,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMagnetDataByCardUUID = `-- name: ListMagnetDataByCardUUID :many
SELECT
    uuid,
    uuid_card,
    track_no,
    content,
    created_at
FROM card_platform_magnet_data
WHERE uuid_card = ?
ORDER BY track_no ASC
`

func (q *Queries) ListMagnetDataByCardUUID(ctx context.Context, uuidCard string) ([]CardPlatformMagnetDatum, error) {
	rows, err := q.db.QueryContext(ctx, listMagnetDataByCardUUID, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformMagnetDatum{}
	for rows.Next() {
		var i CardPlatformMagnetDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.TrackNo,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMagnetDataContent = `-- name: UpdateMagnetDataContent :exec
UPDATE card_platform_magnet_data
SET
    content = ?
WHERE uuid = ?
`

type UpdateMagnetDataContentParams struct {
	Content []byte `json:"content"`
	Uuid    string `json:"uuid"`
}

func (q *Queries) UpdateMagnetDataContent(ctx context.Context, arg UpdateMagnetDataContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMagnetDataContent, arg.Content, arg.Uuid)
	return err
}

const upsertMagnetData = `-- name: UpsertMagnetData :exec
INSERT INTO card_platform_magnet_data (
    uuid,
    uuid_card,
    track_no,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(uuid_card, track_no) DO UPDATE SET
    content = excluded.content
`

type UpsertMagnetDataParams struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	TrackNo   int64  `json:"track_no"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) UpsertMagnetData(ctx context.Context, arg UpsertMagnetDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMagnetData,
		arg.Uuid,
		arg.UuidCard,
		arg.TrackNo,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
