// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mifare_data.sql

package sqlc

import (
	"context"
)

const countMifareDataByCardUUID = `-- name: CountMifareDataByCardUUID :one
SELECT COUNT(*) AS count
FROM card_platform_mifare_data
WHERE uuid_card = ?
`

func (q *Queries) CountMifareDataByCardUUID(ctx context.Context, uuidCard string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMifareDataByCardUUID, uuidCard)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMifareData = `-- name: CreateMifareData :exec
INSERT INTO card_platform_mifare_data (
    uuid,
    uuid_card,
    block_no,
    key_a,
    key_b,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMifareDataParams struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	BlockNo   int64  `json:"block_no"`
	KeyA      []byte `json:"key_a"`
	KeyB      []byte `json:"key_b"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateMifareData(ctx context.Context, arg CreateMifareDataParams) error {
	_, err := q.db.ExecContext(ctx, createMifareData,
		arg.Uuid,
		arg.UuidCard,
		arg.BlockNo,
		arg.KeyA,
		arg.KeyB,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteMifareDataByCardBlock = `-- name: DeleteMifareDataByCardBlock :exec
DELETE FROM card_platform_mifare_data
WHERE uuid_card = ?
  AND block_no = ?
`

type DeleteMifareDataByCardBlockParams struct {
	UuidCard string `json:"uuid_card"`
	BlockNo  int64  `json:"block_no"`
}

func (q *Queries) DeleteMifareDataByCardBlock(ctx context.Context, arg DeleteMifareDataByCardBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteMifareDataByCardBlock, arg.UuidCard, arg.BlockNo)
	return err
}

const deleteMifareDataByCardUUID = `-- name: DeleteMifareDataByCardUUID :exec
DELETE FROM card_platform_mifare_data
WHERE uuid_card = ?
`

func (q *Queries) DeleteMifareDataByCardUUID(ctx context.Context, uuidCard string) error {
	_, err := q.db.ExecContext(ctx, deleteMifareDataByCardUUID, uuidCard)
	return err
}

const deleteMifareDataByUUID = `-- name: DeleteMifareDataByUUID :exec
DELETE FROM card_platform_mifare_data
WHERE uuid = ?
`

func (q *Queries) DeleteMifareDataByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteMifareDataByUUID, uuid)
	return err
}

const getMifareDataByCardBlock = `-- name: GetMifareDataByCardBlock :one
SELECT
    uuid,
    uuid_card,
    block_no,
    key_a,
    key_b,
    content,
    created_at
FROM card_platform_mifare_data
WHERE uuid_card = ?
  AND block_no = ?
LIMIT 1
`

type GetMifareDataByCardBlockParams struct {
	UuidCard string `json:"uuid_card"`
	BlockNo  int64  `json:"block_no"`
}

func (q *Queries) GetMifareDataByCardBlock(ctx context.Context, arg GetMifareDataByCardBlockParams) (CardPlatformMifareDatum, error) {
	row := q.db.QueryRowContext(ctx, getMifareDataByCardBlock, arg.UuidCard, arg.BlockNo)
	var i CardPlatformMifareDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.BlockNo,
		&i.KeyA,
		&i.KeyB,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMifareDataByUUID = `-- name: GetMifareDataByUUID :one
SELECT
    uuid,
    uuid_card,
    block_no,
    key_a,
    key_b,
    content,
    created_at
FROM card_platform_mifare_data
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetMifareDataByUUID(ctx context.Context, uuid string) (CardPlatformMifareDatum, error) {
	row := q.db.QueryRowContext(ctx, getMifareDataByUUID, uuid)
	var i CardPlatformMifareDatum
	err := row.Scan(
		&i.Uuid,
		&i.UuidCard,
		&i.BlockNo,
		&i.KeyA,
		&i.KeyB,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMifareDataByCardUUID = `-- name: ListMifareDataByCardUUID :many
SELECT
    uuid,
    uuid_card,
    block_no,
    key_a,
    key_b,
    content,
    created_at
FROM card_platform_mifare_data
WHERE uuid_card = ?
ORDER BY block_no ASC
`

func (q *Queries) ListMifareDataByCardUUID(ctx context.Context, uuidCard string) ([]CardPlatformMifareDatum, error) {
	rows, err := q.db.QueryContext(ctx, listMifareDataByCardUUID, uuidCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CardPlatformMifareDatum{}
	for rows.Next() {
		var i CardPlatformMifareDatum
		if err := rows.Scan(
			&i.Uuid,
			&i.UuidCard,
			&i.BlockNo,
			&i.KeyA,
			&i.KeyB,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMifareDataContent = `-- name: UpdateMifareDataContent :exec
UPDATE card_platform_mifare_data
SET
    key_a = ?,
    key_b = ?,
    content = ?
WHERE uuid = ?
`

type UpdateMifareDataContentParams struct {
	KeyA    []byte `json:"key_a"`
	KeyB    []byte `json:"key_b"`
	Content []byte `json:"content"`
	Uuid    string `json:"uuid"`
}

func (q *Queries) UpdateMifareDataContent(ctx context.Context, arg UpdateMifareDataContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMifareDataContent,
		arg.KeyA,
		arg.KeyB,
		arg.Content,
		arg.Uuid,
	)
	return err
}

const upsertMifareData = `-- name: UpsertMifareData :exec
INSERT INTO card_platform_mifare_data (
    uuid,
    uuid_card,
    block_no,
    key_a,
    key_b,
    content,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uuid_card, block_no) DO UPDATE SET
    key_a = excluded.key_a,
    key_b = excluded.key_b,
    content = excluded.content
`

type UpsertMifareDataParams struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	BlockNo   int64  `json:"block_no"`
	KeyA      []byte `json:"key_a"`
	KeyB      []byte `json:"key_b"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) UpsertMifareData(ctx context.Context, arg UpsertMifareDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertMifareData,
		arg.Uuid,
		arg.UuidCard,
		arg.BlockNo,
		arg.KeyA,
		arg.KeyB,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
