// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Card struct {
	Uuid           string         `json:"uuid"`
	UuidOrder      string         `json:"uuid_order"`
	HasLaser       int64          `json:"has_laser"`
	HasMagnet      int64          `json:"has_magnet"`
	HasMifareUid   int64          `json:"has_mifare_uid"`
	HasMifare      int64          `json:"has_mifare"`
	HasJavaCard    int64          `json:"has_java_card"`
	HasPress       int64          `json:"has_press"`
	HasTemperature int64          `json:"has_temperature"`
	IsDone         int64          `json:"is_done"`
	Description    sql.NullString `json:"description"`
	CreatedAt      int64          `json:"created_at"`
	UpdatedAt      int64          `json:"updated_at"`
}

type CardStatusHistory struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
}

type LaserDatum struct {
	Uuid        string `json:"uuid"`
	UuidCard    string `json:"uuid_card"`
	Side        string `json:"side"`
	RowNo       int64  `json:"row_no"`
	ContentType string `json:"content_type"`
	Content     []byte `json:"content"`
	CreatedAt   int64  `json:"created_at"`
}

type MagnetDatum struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	TrackNo   int64  `json:"track_no"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

type MifareDatum struct {
	Uuid      string `json:"uuid"`
	UuidCard  string `json:"uuid_card"`
	BlockNo   int64  `json:"block_no"`
	KeyA      []byte `json:"key_a"`
	KeyB      []byte `json:"key_b"`
	Content   []byte `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

type Order struct {
	Uuid        string         `json:"uuid"`
	OrderName   string         `json:"order_name"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
	OrderDate   int64          `json:"order_date"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}
