// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*) AS count
FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByStatus = `-- name: CountOrdersByStatus :one
SELECT COUNT(*) AS count
FROM orders
WHERE status = ?
`

func (q *Queries) CountOrdersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
    uuid,
    order_name,
    status,
    description,
    order_date,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	Uuid        string         `json:"uuid"`
	OrderName   string         `json:"order_name"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
	OrderDate   int64          `json:"order_date"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.Uuid,
		arg.OrderName,
		arg.Status,
		arg.Description,
		arg.OrderDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOrderByUUID = `-- name: DeleteOrderByUUID :exec
DELETE FROM orders
WHERE uuid = ?
`

func (q *Queries) DeleteOrderByUUID(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, deleteOrderByUUID, uuid)
	return err
}

const getOrderByName = `-- name: GetOrderByName :one
SELECT
    uuid,
    order_name,
    status,
    description,
    order_date,
    created_at,
    updated_at
FROM orders
WHERE order_name = ?
LIMIT 1
`

func (q *Queries) GetOrderByName(ctx context.Context, orderName string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByName, orderName)
	var i Order
	err := row.Scan(
		&i.Uuid,
		&i.OrderName,
		&i.Status,
		&i.Description,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUUID = `-- name: GetOrderByUUID :one
SELECT
    uuid,
    order_name,
    status,
    description,
    order_date,
    created_at,
    updated_at
FROM orders
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetOrderByUUID(ctx context.Context, uuid string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByUUID, uuid)
	var i Order
	err := row.Scan(
		&i.Uuid,
		&i.OrderName,
		&i.Status,
		&i.Description,
		&i.OrderDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
    uuid,
    order_name,
    status,
    description,
    order_date,
    created_at,
    updated_at
FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Uuid,
			&i.OrderName,
			&i.Status,
			&i.Description,
			&i.OrderDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT
    uuid,
    order_name,
    status,
    description,
    order_date,
    created_at,
    updated_at
FROM orders
WHERE status = ?
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByStatus(ctx context.Context, status string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.Uuid,
			&i.OrderName,
			&i.Status,
			&i.Description,
			&i.OrderDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderDescription = `-- name: UpdateOrderDescription :exec
UPDATE orders
SET
    description = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateOrderDescriptionParams struct {
	Description sql.NullString `json:"description"`
	UpdatedAt   int64          `json:"updated_at"`
	Uuid        string         `json:"uuid"`
}

func (q *Queries) UpdateOrderDescription(ctx context.Context, arg UpdateOrderDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderDescription, arg.Description, arg.UpdatedAt, arg.Uuid)
	return err
}

const updateOrderInfo = `-- name: UpdateOrderInfo :exec
UPDATE orders
SET
    order_name = ?,
    status = ?,
    description = ?,
    order_date = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateOrderInfoParams struct {
	OrderName   string         `json:"order_name"`
	Status      string         `json:"status"`
	Description sql.NullString `json:"description"`
	OrderDate   int64          `json:"order_date"`
	UpdatedAt   int64          `json:"updated_at"`
	Uuid        string         `json:"uuid"`
}

func (q *Queries) UpdateOrderInfo(ctx context.Context, arg UpdateOrderInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderInfo,
		arg.OrderName,
		arg.Status,
		arg.Description,
		arg.OrderDate,
		arg.UpdatedAt,
		arg.Uuid,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = ?,
    updated_at = ?
WHERE uuid = ?
`

type UpdateOrderStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	Uuid      string `json:"uuid"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.UpdatedAt, arg.Uuid)
	return err
}
